Feat/algorand chain
CoinAlpha/gateway pull request #15
Opened 2023-04-18 07:34 UTC by petioptrv

**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
I am opening this PR so that the Algorand chain code can be peer-reviewed and QA-tested. This code will be part of a larger PR, including the Tinyman connector.

Other than implementing the Algorand chain, this PR also attempts to centralize the places where the chains are being built.

**Tests performed by the developer**:

I have tested all new endpoints.

**Tips for QA testing**:

You can use Pera wallet for Algorand. We already have a funded internal wallet for testing.
Please test the following endpoints for Algorand:
- `/network/status` should return active algorand instances
- `/wallet`, `/wallet/add`, `/wallet/remove` should work as expected for Algorand (`/wallet/sign` not implemented)
- all of the `/algorand/...` endpoints

Please also test creating all other chains as some of the changes in this PR affect chain instantiation. You can do that by simply requesting chain tokens for each chain.

2023-04-18 20:35 UTC, rxlxrxsx commented
Test run: https://hummingbot.testrail.io/index.php?/milestones/view/64

2023-04-20 05:35 UTC, vic-en requested changes

2023-04-20 05:35 UTC, vic-en commented on test-helpers/curl/requests/algorand_balances.json
> +  "address": "FJZ4AJ3EWSNV4PXULFTTT4R5PLMNASEIMWEK5H4EY6E67RGJNSEY7OZEMA",
```suggestion
  "address": "$ALGORAND_ADDRESS",
```

2023-04-20 05:35 UTC, vic-en commented on test-helpers/curl/requests/algorand_opt_in.json
> +  "address": "Y6E7QWFTAI4KWJ4DNSJOLDZ74VU454X5XZLBEPEWMFI7V4GSJ72X3O27HQ",
```suggestion
  "address": "$ALGORAND_ADDRESS",
```

2023-04-20 05:35 UTC, vic-en commented on test-helpers/curl/requests/remove_algorand_key.json
> +  "address": "FJZ4AJ3EWSNV4PXULFTTT4R5PLMNASEIMWEK5H4EY6E67RGJNSEY7OZEMA",
```suggestion
  "address": "$ALGORAND_ADDRESS",
```

2023-04-20 11:39 UTC, petioptrv commented on package.json
> +    "@perp/sdk-curie": "^1.18.0",
It's used by the algorand SDK

2023-04-20 11:40 UTC, petioptrv commented on src/chains/algorand/algorand.ts
> +    // todo: common EVM-like interface
done

2023-04-20 17:44 UTC, vic-en commented on package.json
> +    "@perp/sdk-curie": "^1.18.0",
That can't be the case. Pls double check.

2023-04-20 20:39 UTC, rxlxrxsx approved these changes
Tested and confirmed working by QA.

- Successfully cloned and installed branch
- Setup and run gateway, no issues found
- Export needed variables and run endpoints for algorand and confirmed working
  - Network status and all enpoints for algorand
  - Wallets (except for sign) for algorand
  - Requesting chain tokens for each chain

2023-04-21 00:41 UTC, petioptrv commented on package.json
> +    "@perp/sdk-curie": "^1.18.0",
You're right, reverted

2023-04-24 17:19 UTC, vic-en commented
@petioptrv I think commit [3cd2773](https://github.com/CoinAlpha/gateway/pull/15/commits/3cd277326f8bde399b1fed278e51e7a82afdab36) doesn't belong in this pr

2023-05-02 20:54 UTC, vic-en commented
Corresponding pr on foundation - https://github.com/hummingbot/gateway/pull/90
PRP - https://snapshot.org/#/hbot-prp.eth/proposal/0x08a53dead66043ee8e8b0e65229a99b52be2e212a640e992eb72c9b4cd388701

2023-05-02 20:54 UTC, closed without merging