upgrade traderjoe
CoinAlpha/gateway pull request #19
Opened 2023-06-08 23:57 UTC by vic-en

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This pr upgrade TraderJoe to use sdk V2.
[ch41010]

**Tests performed by the developer**:
- Curl test 
- End-to-end testing

**Tips for QA testing**:
- Curl test 
- End-to-end testing

2023-06-09 22:00 UTC, rxlxrxsx approved these changes
Tested and confirmed working by QA.

- Successfully cloned and installed the branch
- Successfully setup gateway
- Tested the endpoints for trader joe using curl and confirmed working as expected
- Connected trader joe and confirmed working as expected
- Confirmed wallet and exchange balances are reflecting correct
- Created a amm_arb strategy and went through initial prompts successfully
- Started the strategy without issues, confirmed orders are created and cancelled based on config
- Trade information are correct based on history command output
- Compared trades in client and connector, no discrepancies found

2023-06-12 08:51 UTC, petioptrv requested changes

2023-06-12 08:51 UTC, petioptrv commented on src/connectors/traderjoe/traderjoe.ts
> +    return Math.floor(new Date().getTime() / 1000) + this._ttl;
This is an interface method. We should keep this as true time to live getter, and create an additional helper `deadline` that will return `Math.floor(new Date().getTime() / 1000) + this.ttl`

2023-06-12 15:59 UTC, petioptrv commented on src/connectors/traderjoe/traderjoe.ts
> +    return Math.floor(new Date().getTime() / 1000) + this._ttl;
This method is called by and passed to a client of the interface in such a way that mandates `ttl` returns a deadline instead for Uniswapish

2023-06-12 15:59 UTC, petioptrv approved these changes
Changes LGTM

2023-06-12 17:54 UTC, vic-en commented
closing in favour of https://github.com/hummingbot/gateway/pull/131

2023-06-12 17:54 UTC, closed without merging